name: Publish Docker image to GHCR

on:
  ## Why doesn't triggering off the release getting published work?
  # release:
  #   types: [ published ]
  
  # Ok, lets just try triggering of a new version tag getting pushed instead.
  push:
    tags:
      - "v*"

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build & push the image
      env:
        REPO: ${{ github.repository }}
      run: |
        VERSION=$(cat version.txt)
        docker build --tag ghcr.io/$REPO:$VERSION --label "org.opencontainers.image.source=https://github.com/$REPO" --label "org.opencontainers.image.version=$VERSION" .
        docker push ghcr.io/$REPO:$VERSION
